services:
  app:
    image: todo-boot:graal
    container_name: todo-boot-compose
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-todo-compose
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todos
