name: Docker Image CI

on:
  push:
    branches: [ "actions/docker" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        run: export TAG=$(date +%s)-ci
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag aquashdw/todo-boot-actions:${TAG}

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker Image
        run: docker push aquashdw/todo-boot-actions:$(date +%s)-ci
